name: build
on:
  push:
    branches:
      - main
      - mc26
    tags:
      - 'v*' # 当你推送 v1.0, v2.0 等标签时触发发布任务

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      mod_version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: build with gradle
        run: chmod +x gradlew && ./gradlew build

      # 这里的目的是找到打出来的 jar 包名字，方便后面发布
      - name: get version
        id: get_version
        run: echo "VERSION=$(ls build/libs/ | grep -v "-sources" | grep -v "-dev" | head -n 1)" >> $GITHUB_OUTPUT

      # 发布逻辑：只有在推送 Tag 时才会运行这一步
      - name: create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 这是 GitHub 自动生成的，不需要你设置